### ISSUE TITLE
jquery `is(:visible)` check doesn't work consistently against JSDOM

### ISSUE THREAD

**Issue by mockdeep** [unindented/custom-jquery-matchers#32]
Was just looking at your library as an alternative to using our own custom matchers and saw something we ran into. We weren't able to use `is(:visible)` to detect visibility against JSDOM, as they don't always set the CSS properties for it to be reliable. For now, we've had to instead just check that `css('display') !== 'none'`.

**Comment by unindented** [comment]
Yeah, `is(:visible)` only works reliably if the element is mounted to the real document. These days I tend to avoid testing visibility at all in my unit tests.

Not sure what I could do with this issue...

**Comment by mockdeep** [comment]
Does checking `css('display')` instead not work?

**Comment by unindented** [comment]
If you hid the element using `display`, sure. What if you hid it using `visibility`? Or you set `opacity` to 0? Or you set the `width` and `height` to 0?

Trying to determine visibility is a fool's errand, I don't think it's worth pursuing in this library. There's a matcher for CSS properties (`toHaveCss`), so if `toBeVisible` doesn't work in a particular scenario I'd recommend using that to create your specific expectation.
