### ISSUE TITLE
Play nice with enzyme?

### ISSUE THREAD

**Issue by mockdeep** [unindented/custom-jquery-matchers#33]
We, unfortunately, have a good deal of legacy jquery living along side a growing React codebase. In trying to use some of the matchers, it would be nice if they played nice with enzyme components. In some cases this is easier because the API between Jquery and Enzyme can be duck-typed, e.g. this will work for both Jquery and Enzyme:

```js
el.prop('disabled') === true;
```

**Comment by unindented** [comment]
For `enzyme` I would recommend this other library [`jasmine-enzyme`](https://github.com/blainekasten/enzyme-matchers/blob/master/packages/jasmine-enzyme/README.md).
