### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gsavoie** [unindented/custom-jquery-matchers#34]
Will you make a new release of jasmine-jquery-matchers that includes those changes ? https://github.com/unindented/custom-jquery-matchers/commit/a76155dfaa6f8e3d59b9b5661969be2545903fdd

It's been a while and there's at least one fix in there that would be useful for us (`Matchers<T>`)

Thanks Daniel.

**Comment by unindented** [comment]
Sorry, I've not been paying attention to my repos. I'll publish today.

**Comment by unindented** [comment]
Just published `v2.0.0`.
