### ISSUE TITLE
jest requires message to be a function instead of String

### ISSUE THREAD

**Issue by jrmichael** [unindented/custom-jquery-matchers#35]
Jest custom matcher API differs from jasmine. I described the possible workaround facebook/jest#5278 but it got rejected due to "no support for jasmine".

**Comment by unindented** [comment]
Ah, I'll work on it. Thanks for the heads up.

**Comment by unindented** [comment]
Just published `v2.0.0`, which should fix the issue.

**Comment by jrmichael** [comment]
I can confirm. It works as expected. Thanks @unindented
